spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.19.186.138:3306/school_service?useSSL=false
    username: root
    password: iloveudss2006
server:
  address: 0.0.0.0
  port: 80
  servlet:
    context-path: /
file:
  upload-dir: /webapp/images/uploads/